name: ChatGPT Code Review
description: ChatGPT Code Review
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  commitSHA:
    description: 'The commit to review.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout main repo.
      uses: actions/checkout@v3.3.0

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x ./build/gradlew
      shell: bash

    - name: Build with Gradle
      run: cd build; ./gradlew runChatGPT -PcommitSHA={{ inputs.commitSHA }}  --info --stacktrace --build-cache
      shell: bash