name: Code review on Push

on:
  push:
    branches: [main]

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: ChatGPT Code Review
        uses: FloriNNic/ChatGPT-code-review@v1.0.0
        with:
          commitMessage: ${{ github.event.head_commit.message }}
          commitUrl: "https://github.com/${{ github.repository }}/actions/${{ github.sha }}"
