name: Code review on Push
on:
  push:
    branches: [main]

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: ChatGPT Code Review
        uses: FloriNNic/ChatGPT-code-review@v1
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        with:
          commitMessage: ${{ github.event.head_commit.message }}
          commitUrl: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "CR: " + ${{ github.event.head_commit.message }}
          git push
