name: Code review on Push
on:
  push:
    branches: [main]

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: ChatGPT Code Review
        uses: FloriNNic/ChatGPT-code-review@v1
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        with:
          commitMessage: ${{ github.event.head_commit.message }}
          commitUrl: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
