name: Code review on Push

on:
  push:
    branches: [main]

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: ChatGPT Code Review
        uses: actions/chatgpt-code-review@v2
        with:
          commitMessage: ${{ github.event.head_commit.message }}
          commitUrl: ${{ github.server_url }}/${{ github.repository }}/actions/${{ github.sha }}
